// ─── HT Fabrication Visualiser — Finish Registry ────────────────
// All 20 named HT finishes with metadata and placeholder texture URLs.
// Import from @/lib/products/finishes

import type { Finish, MetalType } from "@/types";

export const FINISHES: Finish[] = [
  // ── Copper (9) ─────────────────────────────────────────────────

  {
    id: "northumberland",
    slug: "northumberland",
    name: "Northumberland",
    subtitle: "Aged copper with verdigris accents",
    baseMetal: "copper",
    description:
      "A richly aged copper finish with sweeping verdigris accents, inspired by the weathered rooftops of Northumberland's historic buildings.",
    priceModifier: 1.4,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/northumberland/albedo.png",
      normal: "/textures/northumberland/albedo.png",
      roughness: "/textures/northumberland/albedo.png",
      metalness: "/textures/northumberland/albedo.png",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/northumberland/swatch.png",
    galleryImages: [],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "hertfordshire",
    slug: "hertfordshire",
    name: "Hertfordshire",
    subtitle: "Deep aged copper",
    baseMetal: "copper",
    description:
      "A deep, darkly aged copper finish with warm amber undertones and subtle surface variation.",
    priceModifier: 1.3,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-copper.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-copper.jpg",
    galleryImages: [],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "ayrshire",
    slug: "ayrshire",
    name: "Ayrshire",
    subtitle: "Dappled copper with verdigris specs",
    baseMetal: "copper",
    description:
      "A striking dappled copper finish with scattered verdigris speckling — each piece uniquely hand-aged for maximum character.",
    priceModifier: 1.6,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/ayrshire/albedo.png",
      normal: "/textures/ayrshire/albedo.png",
      roughness: "/textures/ayrshire/albedo.png",
      metalness: "/textures/ayrshire/albedo.png",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/ayrshire/swatch.png",
    galleryImages: [],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "cheshire",
    slug: "cheshire",
    name: "Cheshire",
    subtitle: "Rich aged copper",
    baseMetal: "copper",
    description:
      "A rich, full-bodied aged copper finish with warm tones and a characterful patina.",
    priceModifier: 1.4,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-copper.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-copper.jpg",
    galleryImages: [],
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "natural-copper",
    slug: "natural-copper",
    name: "Natural Copper",
    subtitle: "Raw natural copper",
    baseMetal: "copper",
    description:
      "Clean, unaged natural copper with a warm, bright surface. Will develop its own patina over time.",
    priceModifier: 1.0,
    isAged: false,
    lacquerDefault: "gloss",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-copper.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-copper.jpg",
    galleryImages: [],
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "brushed-copper",
    slug: "brushed-copper",
    name: "Brushed Copper",
    subtitle: "Directionally brushed copper",
    baseMetal: "copper",
    description:
      "Copper with a consistent directional brushed finish, giving a refined linear texture.",
    priceModifier: 1.0,
    isAged: false,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-copper.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-copper.jpg",
    galleryImages: [],
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "lightly-burnished-copper",
    slug: "lightly-burnished-copper",
    name: "Lightly Burnished Copper",
    subtitle: "Hand-burnished copper",
    baseMetal: "copper",
    description:
      "Lightly hand-burnished copper with a soft lustre and gentle surface variation.",
    priceModifier: 1.0,
    isAged: false,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-copper.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-copper.jpg",
    galleryImages: [],
    sortOrder: 7,
    isActive: true,
  },
  {
    id: "antique-burnished-copper",
    slug: "antique-burnished-copper",
    name: "Antique Burnished Copper",
    subtitle: "Aged and burnished copper",
    baseMetal: "copper",
    description:
      "Copper aged to an antique tone then carefully burnished to reveal warm highlights across the surface.",
    priceModifier: 1.2,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-copper.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-copper.jpg",
    galleryImages: [],
    sortOrder: 8,
    isActive: true,
  },
  {
    id: "antique-brushed-copper",
    slug: "antique-brushed-copper",
    name: "Antique Brushed Copper",
    subtitle: "Aged and brushed copper",
    baseMetal: "copper",
    description:
      "Copper with a combined antique aged patina and directional brush finish for a nuanced, layered appearance.",
    priceModifier: 1.1,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-copper.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-copper.jpg",
    galleryImages: [],
    sortOrder: 9,
    isActive: true,
  },

  // ── Brass (7) ──────────────────────────────────────────────────

  {
    id: "somerset",
    slug: "somerset",
    name: "Somerset",
    subtitle: "Stained glass effect brass",
    baseMetal: "brass",
    description:
      "A signature HT finish — brass aged to produce extraordinary stained-glass-like colour shifts across the surface.",
    priceModifier: 1.6,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-brass.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-brass.jpg",
    galleryImages: [],
    sortOrder: 10,
    isActive: true,
  },
  {
    id: "wiltshire",
    slug: "wiltshire",
    name: "Wiltshire",
    subtitle: "Classic aged brass",
    baseMetal: "brass",
    description:
      "A classic aged brass finish with warm golden tones and a distinguished patina.",
    priceModifier: 1.4,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-brass.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-brass.jpg",
    galleryImages: [],
    sortOrder: 11,
    isActive: true,
  },
  {
    id: "berkshire",
    slug: "berkshire",
    name: "Berkshire",
    subtitle: "Bronzed brass",
    baseMetal: "brass",
    description:
      "Brass aged to a deep bronzed tone — darker and richer than classic aged brass, with a refined warmth.",
    priceModifier: 1.5,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-brass.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-brass.jpg",
    galleryImages: [],
    sortOrder: 12,
    isActive: true,
  },
  {
    id: "cambridgeshire",
    slug: "cambridgeshire",
    name: "Cambridgeshire",
    subtitle: "Mill brass finish",
    baseMetal: "brass",
    description:
      "A clean mill brass finish with a bright, consistent surface — understated and timeless.",
    priceModifier: 1.3,
    isAged: false,
    lacquerDefault: "gloss",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-brass.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-brass.jpg",
    galleryImages: [],
    sortOrder: 13,
    isActive: true,
  },
  {
    id: "natural-brass",
    slug: "natural-brass",
    name: "Natural Brass",
    subtitle: "Raw natural brass",
    baseMetal: "brass",
    description:
      "Clean, unaged natural brass. Bright and warm, it will mellow naturally over time.",
    priceModifier: 1.0,
    isAged: false,
    lacquerDefault: "gloss",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-brass.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-brass.jpg",
    galleryImages: [],
    sortOrder: 14,
    isActive: true,
  },
  {
    id: "antique-brass",
    slug: "antique-brass",
    name: "Antique Brass",
    subtitle: "Antique aged brass",
    baseMetal: "brass",
    description:
      "Brass with a full antique patina — dark in the recesses, warm and glowing on high points.",
    priceModifier: 1.5,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/antique-brass/albedo.png",
      normal: "/textures/antique-brass/albedo.png",
      roughness: "/textures/antique-brass/albedo.png",
      metalness: "/textures/antique-brass/albedo.png",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/antique-brass/swatch.png",
    galleryImages: [],
    sortOrder: 15,
    isActive: true,
  },
  {
    id: "antique-brushed-brass",
    slug: "antique-brushed-brass",
    name: "Antique Brushed Brass",
    subtitle: "Aged and brushed brass",
    baseMetal: "brass",
    description:
      "Brass aged to an antique tone with a subsequent directional brush to reveal warm metallic highlights.",
    priceModifier: 1.5,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2, 1.5],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-brass.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-brass.jpg",
    galleryImages: [],
    sortOrder: 16,
    isActive: true,
  },

  // ── Zinc (2) ───────────────────────────────────────────────────

  {
    id: "lightly-aged-zinc",
    slug: "lightly-aged-zinc",
    name: "Lightly Aged Zinc",
    subtitle: "Lightly aged zinc",
    baseMetal: "zinc",
    description:
      "Zinc with a light, even ageing — cool grey tones with a subtle patina that feels understated and contemporary.",
    priceModifier: 1.3,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-zinc.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-zinc.jpg",
    galleryImages: [],
    sortOrder: 17,
    isActive: true,
  },
  {
    id: "antique-zinc",
    slug: "antique-zinc",
    name: "Antique Zinc",
    subtitle: "Antique aged zinc",
    baseMetal: "zinc",
    description:
      "Zinc aged to a deeper antique tone — rich greys with mottled surface variation that reads as authentically old.",
    priceModifier: 1.4,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.7, 0.9, 1.2],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-zinc.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-zinc.jpg",
    galleryImages: [],
    sortOrder: 18,
    isActive: true,
  },

  // ── Steel (2) ──────────────────────────────────────────────────

  {
    id: "blackened-steel",
    slug: "blackened-steel",
    name: "Blackened Steel",
    subtitle: "Heat-blackened steel",
    baseMetal: "steel",
    description:
      "Steel blackened through a controlled heat process — deep, moody tones with a slightly iridescent surface quality.",
    priceModifier: 1.8,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.9, 1.2, 1.5, 2.0],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-steel.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-steel.jpg",
    galleryImages: [],
    sortOrder: 19,
    isActive: true,
  },
  {
    id: "corten-weathered",
    slug: "corten-weathered",
    name: "Corten Weathered",
    subtitle: "Weathered corten steel",
    baseMetal: "corten",
    description:
      "Corten steel with its signature weathered rust patina — warm orange-brown tones that are both industrial and organic.",
    priceModifier: 1.8,
    isAged: true,
    lacquerDefault: "matte",
    availableThicknesses: [0.9, 1.2, 1.5, 2.0],
    maxSheetWidth: 2000,
    maxSheetHeight: 1000,
    textures: {
      albedo: "/textures/placeholder-steel.jpg",
      normal: "/textures/placeholder-normal.jpg",
      roughness: "/textures/placeholder-roughness.jpg",
      metalness: "/textures/placeholder-metalness.jpg",
      realWorldWidthMm: 500,
      realWorldHeightMm: 500,
    },
    swatchImageUrl: "/textures/placeholder-steel.jpg",
    galleryImages: [],
    sortOrder: 20,
    isActive: true,
  },
];

// ─── Helper Functions ────────────────────────────────────────────

/** Returns all active finishes */
export function getActiveFinishes(): Finish[] {
  return FINISHES.filter((f) => f.isActive);
}

/** Returns active finishes for a given metal type */
export function getFinishesByMetal(metal: MetalType): Finish[] {
  return FINISHES.filter((f) => f.isActive && f.baseMetal === metal);
}

/** Finds a finish by its id */
export function getFinishById(id: string): Finish | undefined {
  return FINISHES.find((f) => f.id === id);
}

/** Finds a finish by its slug */
export function getFinishBySlug(slug: string): Finish | undefined {
  return FINISHES.find((f) => f.slug === slug);
}

/** Returns the unique metal types that have at least one active finish */
export function getAvailableMetals(): MetalType[] {
  const metals = new Set<MetalType>(
    FINISHES.filter((f) => f.isActive).map((f) => f.baseMetal)
  );
  return Array.from(metals);
}
